### PR TITLE
Added freemarker support

### PR DESCRIPTION
**Pull request by edwardgronroos**
Added support to choose freemarker as template engine.

Will make another PR that support creating a app with Freemarker, just want to get the app on the market first.

### CODE REVIEW

**Comment by edwardgronroos** [comment]
Any preferences about the tests? Now it fails when trying to parse JS files that contains ejs syntax.

**Comment by ljl** [comment]
Hello. I didnt get any notification about this so sorry for the late reply!

I have a feeling that the parsing might fail because the stored template preference isn't accessible when testing.

I found that the test helper can send in options, maybe that will help?
Ie: `.withOptions({ renderEngine: 'freemarker', templateExtension: 'ftl' })`

**Comment by edwardgronroos** [comment]
That would be usefull to write test to verify the Freemarker generation result is as expected, but the issue now seems to be that the template engine in Yeoman parses the `.js` template as pure JS and then the `ejs` syntax brakes the test.

```JS
var libs = {
  portal: require('/lib/xp/portal'),
  <%= renderEngine %>: require('/lib/xp/<%= renderEngine %>')
};
```

works when running... but test fails since it tries to validate it as JS.

I'll look more into potential options being passed in to the test/template engine.
https://github.com/SBoudrias/mem-fs-editor#copyfrom-to-options

**Comment by ljl** [comment]
My thought was that it was parsed after replacements had been done (this can be tested using a prompt ie. 'name' to make it invalid) and that the renderEngine and TemplateExtension values was not set during test. To me it doesn't make sense if it tries to validate the template pre-replacements.

I can look further into it tonight and post my findings

**Comment by ljl** [comment]
Actually, after reading the build log. It seems like the gulp task pre-test – which is used for reporting testcoverage that fails. If it is indeed the case, I support removing the coverage report for now.

**Comment by edwardgronroos** [comment]
Ahh, looks right yes and that the pre-test tries to parse the js files that contain ejs code.
Could perhaps just rename all templates to use the ejs extension and then when copying-moving them removing it after they been processed?
`_page.xml` to `_page.xml.ejs`, then the pre-test will check the code that is actually real JS and not templates.

What do you think about that solution?

**Pull request merged**
